URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at /opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/hexo-server/lib/middlewares/route.js:20:28
    at call (/opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/connect/index.js:239:7)
    at next (/opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/connect/index.js:183:5)
    at /opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/hexo-server/lib/middlewares/header.js:9:5
    at call (/opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/connect/index.js:239:7)
    at next (/opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/connect/index.js:183:5)
    at Function.handle (/opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/connect/index.js:186:3)
    at Server.app (/opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/connect/index.js:51:37)
    at Server.emit (node:events:390:28)
    at parserOnIncoming (node:_http_server:951:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at /opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/hexo-server/lib/middlewares/route.js:20:28
    at call (/opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/connect/index.js:239:7)
    at next (/opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/connect/index.js:183:5)
    at /opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/hexo-server/lib/middlewares/header.js:9:5
    at call (/opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/connect/index.js:239:7)
    at next (/opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/connect/index.js:183:5)
    at Function.handle (/opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/connect/index.js:186:3)
    at Server.app (/opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/connect/index.js:51:37)
    at Server.emit (node:events:390:28)
    at parserOnIncoming (node:_http_server:951:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at /opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/hexo-server/lib/middlewares/route.js:20:28
    at call (/opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/connect/index.js:239:7)
    at next (/opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/connect/index.js:183:5)
    at /opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/hexo-server/lib/middlewares/header.js:9:5
    at call (/opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/connect/index.js:239:7)
    at next (/opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/connect/index.js:183:5)
    at Function.handle (/opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/connect/index.js:186:3)
    at Server.app (/opt/workplace/pro/python4office.cn/hexo/hexo/node_modules/connect/index.js:51:37)
    at Server.emit (node:events:390:28)
    at parserOnIncoming (node:_http_server:951:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
